# fly.toml app configuration file generated for bus-ticket-demo on 2025-06-24T12:00:00Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'bus-ticket-demo'
primary_region = 'mia'
console_command = '/bin/bash'

[build]
  dockerfile = 'Dockerfile'

[env]
  ASPNETCORE_ENVIRONMENT = 'Production'
  ASPNETCORE_URLS = 'http://0.0.0.0:80'

[[services]]
  protocol = 'tcp'
  internal_port = 80
  processes = ['app']

  [[services.ports]]
    port = 80
    handlers = ['http']
    force_https = true

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

  [services.concurrency]
    type = 'connections'
    hard_limit = 25
    soft_limit = 20

  [[services.tcp_checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '1s'

  [[services.http_checks]]
    interval = '10s'
    timeout = '2s'
    grace_period = '5s'
    method = 'get'
    path = '/api/BusBooking/GetAllBusLocations'
    protocol = 'http'
    tls_skip_verify = false

[mounts]
  source = 'bus_ticket_data'
  destination = '/var/opt/mssql/data'
